### ISSUE TITLE
Mettre en place les différents fichiers template (layout,html, menu.html) et adapter le dossier créer avec init.

### ISSUE THREAD

**Issue by tomicmario** [gen-classroom/projet-ngueukam_parrino_tomic_lopes#45]
La commande init va créer un dossier supplémentaire nommé "template", contenant les fichiers layout.html et menu.html. 

Le fichier layout.html se présente de la manière suivante (edit l'issue pour copier/coller) :

<html lang="en">
<head>
 <meta charset="utf-8">
 <title>{{ site.titre }} | {{ page.titre }}</title>
</head>
<body>
 {% include menu.html }
 {{ content }}
 </body>
</html>

Le fichier menu.html (edit l'issue pour copier/coller) :

<ul>
 <li><a href="/index.html">home</a></li>
 <li><a href="/content/page.html">page</a></li>
</ul>

Temps estimé : 1 heure réaliste, 30 minutes optimiste, 2 heures pessimiste.

**Comment by Alessandro-AP** [comment]
Done
