### ISSUE TITLE
Créer une classe permettant d'injecter une chaîne de caractère, dans un fichier donné à un endroit donnée

### ISSUE THREAD

**Issue by tomicmario** [gen-classroom/projet-ngueukam_parrino_tomic_lopes#46]
L'exemple donné dans le sprint nous indique qu'il existe deux "endroits" où injecter :
- Les variables, qui sont spécifiées au format {{ NOM }}
- Les inclusions de fichier, spécifié au format { % include FICHIER }

Le nom de la classe par défaut est Inject. 

Temps estimé : 3 heures réaliste, 1 h 30 optimiste, 6 heures pessimiste.

**Comment by Alessandro-AP** [comment]
Done
