### ISSUE TITLE
Adapter Build, afin que les injections nécessaires s'effectuent.

### ISSUE THREAD

**Issue by tomicmario** [gen-classroom/projet-ngueukam_parrino_tomic_lopes#49]
Pré-requis : #45 #46 

Lors de la génération du fichier page.html (commande build), le générateur de site statique doit utiliser le moteur de 
template et le fichier layout.html pour :
• injecter la propriété titre du fichier config.yaml dans la variable {{ site.titre }},
• injecter la propriété titre du fichier page.md dans la variable {{ page.titre }},
• inclure le fichier menu.html dans la page,
• injecter le HTML produit par la compilation du fichier markdown page.md dans la variable {{ content }}.

Temps estimé : 1 h 30 réaliste, 45 minutes optimiste, 3 heures pessimiste.

**Comment by Alessandro-AP** [comment]
Done
